branch-defaults:
  default:
    environment: megaenviron-t3
    group_suffix: null
global:
  application_name: mega-t1
  branch: null
  default_ec2_keyname: null
  default_platform: python3.4
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
